### ISSUE TITLE
Provide more insight into CI runs if possible

### ISSUE THREAD

**Issue by carlosmmatos** [CrowdStrike/puppet-falcon#12]
Is there a way to get more information/output as to what the puppet module/tests are doing? Could we be able to see what version of falcon-sensor, or OS information, or other pertinent facts as an output?

**Comment by ffalor** [comment]
Falcon version should be possible, we will just need to add debug messages in the custom resources. What other os information are you thinking about.

**Comment by ffalor** [comment]
#14 adds debug messages and updated the pipelines to use `--debug` to print verbose information about the tests
