### ISSUE TITLE
ubuntu query now expects `16/18/20/22`

### ISSUE THREAD

**Issue by ffalor** [CrowdStrike/puppet-falcon#28]
The query to download ubuntu agents now expects an os_version of `16/18/20/22`. Old packages still expect `16/18/20`.

This is preventing new Ubuntu versions from being downloaded.

**Comment by isimluk** [comment]
When you are on this, can You please take a look into the following issue?

`git grep 'RHEL/CentOS/Oracle'` -> these places may need to be amended as the latest ARM sensor for RHEL8 is published under slightly different label.
