### ISSUE TITLE
Fails to install on a Windows Server

### ISSUE THREAD

**Issue by Tamerz** [CrowdStrike/puppet-falcon#47]
I get the following error when trying to use this to install on a Windows Server 2022 machine:

```
Error: Could not set 'present' on ensure: No such file or directory @ rb_sysopen - C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/puppet_x/../../../metadata.json (file: /etc/puppetlabs/code/environments/production/modules/falcon/manifests/install.pp, line: 26)
```

I'm using the API install method. The only class variables I am setting are `cid`, `client_id`, and `client_secret` which are set using Hiera.

We are using Puppet Enterprise 2019.8.11 with Puppet agent version: 6.27.0

EDIT: Same failure on a Windows Server 2019 machine.

**Comment by ffalor** [comment]
thanks for reporting this ill get a fix out soon

**Comment by ffalor** [comment]
thanks again for reporting this - 0.5.1 should fix the issue.

I do testing on windows via a local install and run, but this issue only arises when using a puppet server. I'll add this to testing to prevent something like this from happening in the future.

**Comment by Tamerz** [comment]
Works perfect now. Thanks!
