### ISSUE TITLE
Proxy support for API installs

### ISSUE THREAD

**Issue by maoneal** [CrowdStrike/puppet-falcon#70]
(This is related to Linux installs using the API - my systems require going through a proxy to get to the Internet.)

Code supports setting proxy configuration for the sensor to function with, but the actual API installation method does not use those same proxy settings during the installation.  I reviewed `lib/puppet/puppet_x/falconapi.rb` but ran into limitations with my Ruby programming knowledge in how to attach proxy configs to the `Net::HTTP` calls, so unfortunately could not attach a patch to assist.

**Comment by ffalor** [comment]
Good find, let me think about this for a moment and confer with my team.

**Comment by ffalor** [comment]
@maoneal It looks like [Ruby `Net::HTTP`](https://ruby-doc.org/stdlib-2.4.2/libdoc/net/http/rdoc/Net/HTTP.html) will respect the `HTTP_PROXY` environment variable route traffic through that value.

I'll continue to work on seeing how this will fit into the module, but in the meantime I wanted to throw that option out to you.

**Comment by maoneal** [comment]
I saw that in the documentation as well - we have environmental variables set, but they aren't being used by the Puppet process, so unclear why that is.

**Comment by ffalor** [comment]
Hey @maoneal #89 adds two new params to the module

`sensor_dl_proxy_host`
`sensor_dl_proxy_port`

The `http_client` in `lib/puppet/puppet_x/falconapi.rb` will use the host and port provided by these two new parameters.

The latest puppet module release [`v0.10.0`](https://forge.puppet.com/modules/crowdstrike/falcon/readme) contains these changes.
